# Generated by Django 5.1.2 on 2024-11-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('epidemic', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('not_verified', 'Not Verified'), ('verified', 'Verified')], default='not_verified', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
